import { SEO_LANDING_PAGES, type SeoLandingPageConfig, type SeoLandingSlug } from './seoPages';

const germanCopy: Record<string, string> = {
  'Strava activity to video': 'Strava-Aktivität zum Video',
  'Turn a Strava Activity Into a 3D Route Video': 'Verwandeln Sie eine Strava-Aktivität in ein 3D-Routenvideo',
  'Export your Strava GPX, replay the real route in 3D, and download a polished video with stats and elevation.': 'Exportieren Sie Ihr Strava-GPX, spielen Sie die tatsächliche Route in 3D ab und laden Sie ein ausgefeiltes Video mit Statistiken und Höhenmetern herunter.',
  'Built for real activity data, not a hand-drawn travel line.': 'Gebaut für echte Aktivitätsdaten, nicht für eine handgezeichnete Reiselinie.',
  'From Strava activity to MP4': 'Von der Strava-Aktivität zu MP4',
  'You keep control of the original file. TrailReplay processes the GPX locally in your browser.': 'Sie behalten die Kontrolle über die Originaldatei. TrailReplay verarbeitet die GPX-Datei lokal in Ihrem Browser.',
  'Export the activity': 'Aktivität exportieren',
  'Open your activity on Strava.com, choose Export GPX, and save the file.': 'Öffnen Sie Ihre Aktivität auf Strava.com, wählen Sie „GPX exportieren“ und speichern Sie die Datei.',
  'Drop in the GPX': 'GPX-Datei ablegen',
  'Import it into TrailReplay. Distance, elevation, timestamps, and route geometry are read automatically.': 'Importieren Sie sie in TrailReplay. Distanz, Höhenmeter, Zeitstempel und Streckenverlauf werden automatisch eingelesen.',
  'Shape the replay': 'Wiedergabe gestalten',
  'Choose the map, camera, trail style, statistics, speed, annotations, and export frame.': 'Wählen Sie Karte, Kamera, Streckenstil, Statistiken, Geschwindigkeit, Anmerkungen und Exportformat.',
  'Download the video': 'Video herunterladen',
  'Record an MP4 or WebM ready for editing, YouTube, Instagram, or your ride recap.': 'Nehmen Sie ein MP4 oder WebM auf – bereit für Schnitt, YouTube, Instagram oder Ihren Tourenrückblick.',
  'A replay that still feels like your activity': 'Eine Wiedergabe, die sich wie Ihre Aktivität anfühlt',
  'Recorded route': 'Aufgezeichnete Strecke',
  'Animate the GPX line from the activity you actually completed.': 'Animieren Sie die GPX-Linie der Aktivität, die Sie tatsächlich absolviert haben.',
  'Real statistics': 'Echte Statistiken',
  'Show distance, elevation, pace, speed, and progress where the file supports them.': 'Zeigen Sie Distanz, Höhenmeter, Tempo, Geschwindigkeit und Fortschritt, sofern die Datei diese Daten enthält.',
  'Terrain-aware 3D': '3D mit Geländebezug',
  'Use terrain, camera movement, and elevation to give the route geographical context.': 'Nutzen Sie Gelände, Kamerabewegung und Höhenmeter, um die Strecke geografisch einzuordnen.',
  'How to export a GPX from Strava': 'So exportieren Sie eine GPX-Datei aus Strava',
  'On the Strava website, open one of your own activities, select the three-dot action menu, and choose Export GPX. Strava may limit GPX export for activities that do not belong to you.': 'Öffnen Sie auf der Strava-Website eine eigene Aktivität, wählen Sie das Drei-Punkte-Menü und anschließend „GPX exportieren“. Für Aktivitäten anderer Personen kann Strava den GPX-Export einschränken.',
  'A timestamped activity file produces the most faithful replay. If timestamps are unavailable, TrailReplay can still visualize the route and create an animation using the playback settings you choose.': 'Eine Aktivitätsdatei mit Zeitstempeln liefert die genaueste Wiedergabe. Ohne Zeitstempel kann TrailReplay die Strecke dennoch visualisieren und mit Ihren Wiedergabeeinstellungen animieren.',
  'Does TrailReplay connect to my Strava account?': 'Verbindet sich TrailReplay mit meinem Strava-Konto?',
  'No. Download the GPX from Strava and import it yourself; no Strava login or account connection is required.': 'Nein. Laden Sie die GPX-Datei von Strava herunter und importieren Sie sie selbst. Ein Strava-Login oder eine Kontoverbindung ist nicht erforderlich.',
  'Can I use a Strava route instead of an activity?': 'Kann ich statt einer Aktivität eine Strava-Route verwenden?',
  'Yes, if you can export it as GPX. Activity files usually contain richer timing data.': 'Ja, sofern Sie sie als GPX exportieren können. Aktivitätsdateien enthalten meist detailliertere Zeitdaten.',
  'Is my Strava GPX uploaded?': 'Wird meine Strava-GPX-Datei hochgeladen?',
  'The route is parsed locally in your browser by default and is not uploaded to TrailReplay servers.': 'Die Strecke wird standardmäßig lokal in Ihrem Browser verarbeitet und nicht auf TrailReplay-Server hochgeladen.',
  'Garmin activity to video': 'Garmin-Aktivität zum Video',
  'Turn a Garmin Activity Into a 3D Route Video': 'Verwandeln Sie eine Garmin-Aktivität in ein 3D-Routenvideo',
  'Export GPX from Garmin Connect and create an animated route replay with terrain, elevation, statistics, photos, and video export.': 'Exportieren Sie eine GPX-Datei aus Garmin Connect und erstellen Sie eine animierte Streckenwiedergabe mit Gelände, Höhenmetern, Statistiken, Fotos und Videoexport.',
  'Works from a standard GPX export. No Garmin account connection needed.': 'Funktioniert mit einem Standard-GPX-Export. Keine Garmin-Kontoverbindung nötig.',
  'Create a Garmin route replay': 'Garmin-Streckenwiedergabe erstellen',
  'Start with the original activity export to preserve as much route and timing detail as possible.': 'Beginnen Sie mit dem originalen Aktivitätsexport, um möglichst viele Strecken- und Zeitdetails zu erhalten.',
  'Open Garmin Connect': 'Garmin Connect öffnen',
  'Open the completed activity on the Garmin Connect website.': 'Öffnen Sie die abgeschlossene Aktivität auf der Garmin-Connect-Website.',
  'Export the GPX': 'GPX-Datei exportieren',
  'Use the activity settings menu and select Export to GPX.': 'Öffnen Sie das Aktivitätsmenü und wählen Sie „Als GPX exportieren“.',
  'Customize the route': 'Strecke anpassen',
  'Import the file, choose the map and camera, and add stats, elevation, photos, or text.': 'Importieren Sie die Datei, wählen Sie Karte und Kamera und ergänzen Sie Statistiken, Höhenmeter, Fotos oder Text.',
  'Export your replay': 'Wiedergabe exportieren',
  'Record a landscape, square, or vertical route video for your preferred channel.': 'Nehmen Sie ein Streckenvideo im Querformat, Quadrat oder Hochformat für Ihren bevorzugten Kanal auf.',
  'Use the detail your Garmin recorded': 'Nutzen Sie die Details, die Ihr Garmin aufgezeichnet hat',
  'Activity-first': 'Aus der Aktivität heraus',
  'Build the story around the route and timestamps captured by your device.': 'Bauen Sie die Geschichte aus der Strecke und den Zeitstempeln auf, die Ihr Gerät aufgezeichnet hat.',
  'Sport statistics': 'Sportstatistiken',
  'Display useful motion and route metrics in the exported video.': 'Zeigen Sie im exportierten Video aussagekräftige Bewegungs- und Streckenwerte an.',
  'Flexible output': 'Flexibler Export',
  'Choose MP4 or WebM with export settings for different aspect ratios and quality levels.': 'Wählen Sie MP4 oder WebM mit Exporteinstellungen für verschiedene Seitenverhältnisse und Qualitätsstufen.',
  'Exporting from Garmin Connect': 'Export aus Garmin Connect',
  'Use Garmin Connect in a desktop browser, open the activity detail, select the gear icon, and choose Export to GPX. The exact menu wording can vary as Garmin updates Connect.': 'Nutzen Sie Garmin Connect in einem Desktop-Browser: Öffnen Sie die Aktivitätsdetails, wählen Sie das Zahnradsymbol und dann „Als GPX exportieren“. Die genaue Menübezeichnung kann sich mit Garmin Connect ändern.',
  'GPX is ideal for route geometry and broadly compatible timestamps. If you only have a FIT file, export or convert it to GPX before importing it into TrailReplay.': 'GPX eignet sich ideal für Streckenverläufe und kompatible Zeitstempel. Wenn Sie nur eine FIT-Datei haben, exportieren oder konvertieren Sie sie vor dem Import in TrailReplay zu GPX.',
  'Does this work with Garmin watches and bike computers?': 'Funktioniert das mit Garmin-Uhren und Fahrradcomputern?',
  'Yes. If the recorded activity appears in Garmin Connect and can be exported as GPX, TrailReplay can import it.': 'Ja. Wenn die aufgezeichnete Aktivität in Garmin Connect erscheint und als GPX exportiert werden kann, kann TrailReplay sie importieren.',
  'Do I need to install software?': 'Muss ich Software installieren?',
  'No. TrailReplay runs in a modern desktop browser.': 'Nein. TrailReplay läuft in einem modernen Desktop-Browser.',
  'Can I add photos to a Garmin route replay?': 'Kann ich Fotos zu einer Garmin-Streckenwiedergabe hinzufügen?',
  'Yes. Photos can be positioned using GPS or timestamps when metadata is available, or placed manually.': 'Ja. Fotos können bei verfügbaren Metadaten über GPS oder Zeitstempel positioniert oder manuell platziert werden.',
  'Free GPX animation maker': 'Kostenloser GPX-Animationseditor',
  'Animate a GPX File on a 3D Map': 'Eine GPX-Datei auf einer 3D-Karte animieren',
  'Turn a recorded GPS track into a cinematic route animation with terrain, live statistics, elevation, photos, and downloadable video.': 'Verwandeln Sie einen aufgezeichneten GPS-Track in eine filmische Streckenanimation mit Gelände, Live-Statistiken, Höhenmetern, Fotos und herunterladbarem Video.',
  'Free, open source, and processed in your browser.': 'Kostenlos, Open Source und direkt in Ihrem Browser verarbeitet.',
  'Make a GPX animation in minutes': 'Eine GPX-Animation in wenigen Minuten erstellen',
  'No timeline editor is required. Import a route, compose the view, preview it, and record.': 'Kein Timeline-Editor nötig: Importieren Sie eine Strecke, gestalten Sie die Ansicht, sehen Sie sie in der Vorschau an und zeichnen Sie auf.',
  'Import GPX or KML': 'GPX oder KML importieren',
  'Drop one route or combine multiple tracks into a longer journey.': 'Legen Sie eine Strecke ab oder kombinieren Sie mehrere Tracks zu einer längeren Tour.',
  'Choose the map': 'Karte auswählen',
  'Select imagery, terrain, trail color, camera behavior, and the section of the route to show.': 'Wählen Sie Bildmaterial, Gelände, Streckenfarbe, Kameraverhalten und den anzuzeigenden Streckenabschnitt.',
  'Add the story': 'Geschichte ergänzen',
  'Include elevation, statistics, pictures, labels, annotations, or a comparison track.': 'Ergänzen Sie Höhenmeter, Statistiken, Bilder, Beschriftungen, Anmerkungen oder einen Vergleichstrack.',
  'Record the animation': 'Animation aufzeichnen',
  'Export the replay as a video or capture a social-ready still image.': 'Exportieren Sie die Wiedergabe als Video oder erstellen Sie ein Standbild für Social Media.',
  'More than a moving line': 'Mehr als eine bewegte Linie',
  'Map and terrain': 'Karte und Gelände',
  'Put the route in its real landscape with configurable basemaps and 3D terrain.': 'Setzen Sie die Strecke mit konfigurierbaren Basiskarten und 3D-Gelände in ihre reale Landschaft.',
  'Story controls': 'Steuerung für Ihre Story',
  'Control pace, camera, crop, visual style, pictures, and annotations.': 'Steuern Sie Tempo, Kamera, Ausschnitt, visuellen Stil, Bilder und Anmerkungen.',
  'Files you can use': 'Dateien zur Weiterverwendung',
  'Download the result for a video editor or publish it directly.': 'Laden Sie das Ergebnis für einen Videoeditor herunter oder veröffentlichen Sie es direkt.',
  'What makes a good GPX animation?': 'Was macht eine gute GPX-Animation aus?',
  'A clean track, useful timestamps, and a deliberate camera angle matter more than excessive effects. Start with the whole route, then choose a playback speed that keeps the geography readable.': 'Ein sauberer Track, hilfreiche Zeitstempel und ein bewusster Kamerawinkel sind wichtiger als übertriebene Effekte. Beginnen Sie mit der gesamten Strecke und wählen Sie dann eine Wiedergabegeschwindigkeit, bei der die Geografie verständlich bleibt.',
  'For a vertical social post, preview the 9:16 crop before recording. For YouTube or a longer film, landscape output leaves more space for the map and statistics.': 'Sehen Sie sich für einen vertikalen Social-Media-Beitrag den 9:16-Ausschnitt vor der Aufnahme an. Für YouTube oder einen längeren Film bietet das Querformat mehr Platz für Karte und Statistiken.',
  'What is a GPX animation?': 'Was ist eine GPX-Animation?',
  'It is a timed visual replay of GPS coordinates on a map, usually exported as video for sharing or editing.': 'Sie ist eine zeitgesteuerte visuelle Wiedergabe von GPS-Koordinaten auf einer Karte, die meist als Video zum Teilen oder Bearbeiten exportiert wird.',
  'Can I animate more than one GPX?': 'Kann ich mehr als eine GPX-Datei animieren?',
  'Yes. TrailReplay supports multiple tracks, journeys, and separate comparison tracks.': 'Ja. TrailReplay unterstützt mehrere Tracks, Touren und separate Vergleichstracks.',
  'Can TrailReplay export MP4?': 'Kann TrailReplay MP4 exportieren?',
  'Yes, when your browser supports the required encoding path. WebM is available as a fallback.': 'Ja, wenn Ihr Browser den erforderlichen Kodierungspfad unterstützt. WebM steht als Alternative bereit.',
  'Cycling route animation': 'Animation einer Fahrradroute',
  'Create an Animated Cycling Route Video': 'Ein animiertes Fahrradroutenvideo erstellen',
  'Transform a road, gravel, MTB, or bikepacking GPX into a 3D video with speed, elevation, distance, photos, and route progress.': 'Verwandeln Sie eine Rennrad-, Gravel-, MTB- oder Bikepacking-GPX-Datei in ein 3D-Video mit Geschwindigkeit, Höhenmetern, Distanz, Fotos und Streckenfortschritt.',
  'One ride, a multi-day journey, or a head-to-head comparison.': 'Eine Fahrt, eine mehrtägige Tour oder ein direkter Vergleich.',
  'Tell the full story of the ride': 'Die ganze Geschichte der Fahrt erzählen',
  'Use a route from your bike computer or activity platform, then make the geography easy to follow.': 'Nutzen Sie eine Strecke von Ihrem Fahrradcomputer oder Ihrer Aktivitätsplattform und machen Sie die Geografie leicht nachvollziehbar.',
  'Get the ride GPX': 'GPX-Datei der Fahrt besorgen',
  'Export from Garmin, Strava, Komoot, Ride with GPS, or another service.': 'Exportieren Sie von Garmin, Strava, Komoot, Ride with GPS oder einem anderen Dienst.',
  'Frame the terrain': 'Gelände in Szene setzen',
  'Choose a camera and map that make climbs, descents, and switchbacks legible.': 'Wählen Sie eine Kamera und Karte, die Anstiege, Abfahrten und Serpentinen gut lesbar machen.',
  'Add ride context': 'Kontext zur Fahrt ergänzen',
  'Show distance, speed, elevation, progress, pictures, and day-by-day journey segments.': 'Zeigen Sie Distanz, Geschwindigkeit, Höhenmeter, Fortschritt, Bilder und Tagesabschnitte der Tour.',
  'Export for your channel': 'Für Ihren Kanal exportieren',
  'Record landscape for YouTube or vertical and square variants for social posts.': 'Nehmen Sie im Querformat für YouTube oder in Hochformat- und Quadratvarianten für Social Media auf.',
  'Designed for the shape of a ride': 'Für die Besonderheiten einer Fahrt entwickelt',
  'Road to bikepacking': 'Vom Rennrad bis Bikepacking',
  'Use one recorded ride or assemble multiple GPX files into a continuous journey.': 'Nutzen Sie eine aufgezeichnete Fahrt oder verbinden Sie mehrere GPX-Dateien zu einer durchgehenden Tour.',
  'Climbs in context': 'Anstiege im Kontext',
  'Pair 3D terrain and elevation data to show why a route felt hard.': 'Kombinieren Sie 3D-Gelände und Höhendaten, um zu zeigen, warum sich eine Strecke anspruchsvoll anfühlte.',
  'Ride progression': 'Fortschritt der Fahrt',
  'Use timing data and playback controls to communicate the rhythm of the activity.': 'Nutzen Sie Zeitdaten und Wiedergabesteuerung, um den Rhythmus der Aktivität zu vermitteln.',
  'Cycling videos that explain the route': 'Fahrradvideos, die die Strecke erklären',
  'A route animation is useful before the ride as a course overview and after it as part of a recap. It can bridge footage gaps while showing viewers where the next climb, town, or stage fits.': 'Eine Streckenanimation hilft vor der Fahrt als Kursüberblick und danach als Teil eines Rückblicks. Sie überbrückt Lücken im Filmmaterial und zeigt, wo der nächste Anstieg, Ort oder die nächste Etappe liegt.',
  'For long-distance trips, combine daily GPX files into a journey and use annotations or photos to mark stops. For races, add a comparison track to explain two lines or attempts.': 'Kombinieren Sie für Langstreckentouren tägliche GPX-Dateien zu einer Tour und markieren Sie Stopps mit Anmerkungen oder Fotos. Für Rennen können Sie einen Vergleichstrack hinzufügen, um zwei Linien oder Versuche zu erklären.',
  'Can I animate a multi-day bikepacking route?': 'Kann ich eine mehrtägige Bikepacking-Route animieren?',
  'Yes. Import multiple GPX files and organize them as journey segments.': 'Ja. Importieren Sie mehrere GPX-Dateien und organisieren Sie sie als Tourabschnitte.',
  'Can it show speed and elevation?': 'Kann es Geschwindigkeit und Höhenmeter anzeigen?',
  'TrailReplay can display statistics supported by the imported data and calculated route profile.': 'TrailReplay kann Statistiken anzeigen, die von den importierten Daten und dem berechneten Streckenprofil unterstützt werden.',
  'Which cycling platforms work?': 'Welche Fahrradplattformen werden unterstützt?',
  'Any platform that lets you export a standard GPX or KML route can feed TrailReplay.': 'Jede Plattform, aus der Sie eine Standard-GPX- oder KML-Strecke exportieren können, funktioniert mit TrailReplay.',
  'Running route animation': 'Animation einer Laufstrecke',
  'Create an Animated Running Route Video': 'Ein animiertes Laufstreckenvideo erstellen',
  'Turn a road race, marathon, trail run, or ultra GPX into a 3D replay with pace, elevation, distance, photos, and progress.': 'Verwandeln Sie eine GPX-Datei von Straßenrennen, Marathon, Trailrun oder Ultra in eine 3D-Wiedergabe mit Tempo, Höhenmetern, Distanz, Fotos und Fortschritt.',
  'Make the course and the effort understandable at a glance.': 'Machen Sie Strecke und Anstrengung auf einen Blick verständlich.',
  'From finish line to route replay': 'Von der Ziellinie zur Streckenwiedergabe',
  'Start with the activity GPX from your watch or training platform and build the story around the course.': 'Beginnen Sie mit der Aktivitäts-GPX Ihrer Uhr oder Trainingsplattform und erzählen Sie die Geschichte entlang der Strecke.',
  'Export your run': 'Lauf exportieren',
  'Download GPX from Strava, Garmin Connect, Coros, Suunto, or another activity service.': 'Laden Sie GPX-Dateien von Strava, Garmin Connect, Coros, Suunto oder einem anderen Aktivitätsdienst herunter.',
  'Import the course': 'Strecke importieren',
  'TrailReplay reads the route, distance, timing, and available elevation information.': 'TrailReplay liest Strecke, Distanz, Zeitinformationen und verfügbare Höhendaten ein.',
  'Show the effort': 'Anstrengung zeigen',
  'Choose pace, elevation, progress, camera, map style, photos, and annotations.': 'Wählen Sie Tempo, Höhenmeter, Fortschritt, Kamera, Kartenstil, Fotos und Anmerkungen.',
  'Share the result': 'Ergebnis teilen',
  'Export a route video for your race recap, club, coach, film, or social post.': 'Exportieren Sie ein Streckenvideo für Ihren Rennrückblick, Verein, Trainer, Film oder Social-Media-Beitrag.',
  'Made for races, trails, and long days out': 'Für Rennen, Trails und lange Tage draußen gemacht',
  'Any running route': 'Jede Laufstrecke',
  'Use a city 5K, marathon course, mountain trail, or ultra-distance track.': 'Nutzen Sie einen 5-km-Lauf in der Stadt, eine Marathonstrecke, einen Bergtrail oder einen Ultradistanz-Track.',
  'Pace and elevation': 'Tempo und Höhenmeter',
  'Give viewers context for the effort and the shape of the course.': 'Geben Sie Zuschauenden Kontext für die Anstrengung und den Verlauf der Strecke.',
  'Photos on the route': 'Fotos entlang der Strecke',
  'Place race and trail photos by GPS, timestamp, or manual position.': 'Platzieren Sie Renn- und Trailfotos per GPS, Zeitstempel oder manuell.',
  'Make a race recap easier to follow': 'Einen Rennrückblick leichter nachvollziehbar machen',
  'A map replay gives structure to race footage and photographs. Use it as an opening course overview, between aid stations, or as a complete visual summary when you did not record video during the run.': 'Eine Kartenwiedergabe gibt Rennaufnahmen und Fotos Struktur. Nutzen Sie sie als Streckenüberblick zu Beginn, zwischen Verpflegungsstationen oder als vollständige Zusammenfassung, wenn Sie beim Lauf kein Video aufgenommen haben.',
  'Trail and ultra routes benefit from a lower camera angle and visible elevation. Road races usually read better with a cleaner overhead view and a crop that keeps the full course visible.': 'Trail- und Ultra-Strecken profitieren von einem niedrigeren Kamerawinkel und sichtbaren Höhenmetern. Straßenrennen sind mit einer klaren Draufsicht und einem Ausschnitt, der die gesamte Strecke zeigt, meist besser lesbar.',
  'Can I make a marathon route animation?': 'Kann ich eine Marathonstrecken-Animation erstellen?',
  'Yes. Import the race activity GPX, customize the replay, and export it as video.': 'Ja. Importieren Sie die Aktivitäts-GPX des Rennens, passen Sie die Wiedergabe an und exportieren Sie sie als Video.',
  'Does it work for trail running and ultras?': 'Funktioniert es für Trailrunning und Ultras?',
  'Yes. 3D terrain, elevation, journey segments, and photos are especially useful for longer trail events.': 'Ja. 3D-Gelände, Höhenmeter, Tourabschnitte und Fotos sind besonders nützlich für längere Trail-Events.',
  'Can I create a vertical running video?': 'Kann ich ein vertikales Laufvideo erstellen?',
  'Yes. Preview and record a 9:16 crop for Reels, Shorts, and TikTok.': 'Ja. Zeigen Sie eine Vorschau an und zeichnen Sie einen 9:16-Ausschnitt für Reels, Shorts und TikTok auf.',

  // GPX animator page: copy that drifted out of sync with these keys.
  'Free online GPX animator': 'Kostenloser Online-GPX-Animator',
  'GPX Animator: Animate a GPX File on a 3D Map': 'GPX-Animator: Eine GPX-Datei auf einer 3D-Karte animieren',
  'TrailReplay is a free GPX animator that turns a recorded GPS track into a cinematic route animation with terrain, live statistics, elevation, photos, and downloadable video.': 'TrailReplay ist ein kostenloser GPX-Animator, der einen aufgezeichneten GPS-Track in eine filmische Routenanimation verwandelt — mit Gelände, Live-Statistiken, Höhenprofil, Fotos und herunterladbarem Video.',
  'Animate a GPX file in minutes': 'Eine GPX-Datei in Minuten animieren',
  'Unlike animator tools that require a desktop install, TrailReplay runs entirely in the browser: no download, no Java runtime, no OS-specific build. Import a file, compose the view, and export, all in the same tab.': 'Anders als Animationsprogramme, die eine Desktop-Installation verlangen, läuft TrailReplay vollständig im Browser: kein Download, keine Java-Laufzeitumgebung, kein betriebssystemspezifischer Build. Datei importieren, Ansicht gestalten und exportieren — alles im selben Tab.',
  'What is a GPX animator?': 'Was ist ein GPX-Animator?',
  'It is a tool that produces a timed visual replay of GPS coordinates on a map, usually exported as video for sharing or editing.': 'Ein Werkzeug, das GPS-Koordinaten als zeitlich getaktete visuelle Wiedergabe auf einer Karte darstellt, meist als Video zum Teilen oder Weiterbearbeiten exportiert.',
  'Do I need to download or install anything?': 'Muss ich etwas herunterladen oder installieren?',
  'No. TrailReplay is an online GPX animator that runs fully in your browser tab, with no desktop app, Java runtime, or installer required.': 'Nein. TrailReplay ist ein Online-GPX-Animator, der vollständig in Ihrem Browser-Tab läuft — ohne Desktop-App, Java-Laufzeitumgebung oder Installationsprogramm.',
  'Is this the same as a GPX flyover or route replay tool?': 'Ist das dasselbe wie ein GPX-Flyover- oder Routen-Replay-Tool?',
  '"GPX flyover," "route replay," and "GPX animator" all describe the same idea: replaying a recorded route as a moving animation instead of a static line on a map.': '„GPX-Flyover“, „Routen-Replay“ und „GPX-Animator“ beschreiben dieselbe Idee: eine aufgezeichnete Route als bewegte Animation abspielen statt als statische Linie auf einer Karte.',
  'Is TrailReplay a gpx2video alternative?': 'Ist TrailReplay eine Alternative zu gpx2video?',
  'Yes. Like other GPX-to-video tools, TrailReplay converts a track into a shareable video, with 3D terrain, live stats, and photo annotations built in.': 'Ja. Wie andere GPX-zu-Video-Werkzeuge wandelt TrailReplay einen Track in ein teilbares Video um — mit 3D-Gelände, Live-Statistiken und Fotoanmerkungen von Haus aus.',
  // Cinematic camera landing page.
  'Cinematic camera': 'Filmische Kamera',
  'Direct the Camera on Your Own Route Video': 'Führen Sie die Kamera in Ihrem eigenen Routenvideo',
  'Place camera keyframes along the timeline and TrailReplay glides between them — a shot you chose, not a camera that just trails the marker.': 'Setzen Sie Kamera-Keyframes entlang der Zeitleiste, und TrailReplay gleitet zwischen ihnen — eine Einstellung, die Sie gewählt haben, statt einer Kamera, die der Markierung nur hinterherläuft.',
  'The camera follows the line of the route, not every switchback in it.': 'Die Kamera folgt dem Verlauf der Strecke, nicht jeder einzelnen Kehre darin.',
  'Four keys and a ball': 'Vier Tasten und ein Ball',
  'Cinematic mode lives in Map & Camera. Every step below also works from the keyboard, so you can shoot a whole route without touching the mouse.': 'Der filmische Modus liegt unter Karte & Kamera. Jeder Schritt unten funktioniert auch über die Tastatur, sodass Sie eine ganze Route ohne Maus aufnehmen können.',
  'Pause where you want a shot': 'Dort pausieren, wo Sie eine Einstellung wollen',
  'Press Space to pause the replay at the moment you want to frame. The marker stays put while you compose.': 'Drücken Sie die Leertaste, um die Wiedergabe an dem Moment anzuhalten, den Sie einrichten möchten. Die Markierung bleibt stehen, während Sie die Einstellung aufbauen.',
  'Aim the camera': 'Die Kamera ausrichten',
  'Drag the orbit ball, or press A and D to swing around the marker, W and S to raise or lower the camera, R and F to move closer or further away.': 'Ziehen Sie den Orbit-Ball, oder drücken Sie A und D, um die Markierung zu umkreisen, W und S, um die Kamera zu heben oder zu senken, und R und F, um näher heran- oder weiter wegzugehen.',
  'Save the shot': 'Die Einstellung speichern',
  'Press Enter, or the Set camera keyframe button. Press Enter again at the same moment to update that shot rather than adding a second one.': 'Drücken Sie Enter oder die Schaltfläche „Kamera-Keyframe setzen“. Ein erneutes Enter am selben Moment aktualisiert diese Einstellung, statt eine zweite anzulegen.',
  'Move on and repeat': 'Weiterspringen und wiederholen',
  'Scrub to the next moment and frame it. Between two keyframes the camera glides smoothly from one to the other.': 'Springen Sie zum nächsten Moment und richten Sie ihn ein. Zwischen zwei Keyframes gleitet die Kamera weich von einem zum anderen.',
  'Why it looks calmer than a camera that follows': 'Warum das ruhiger wirkt als eine folgende Kamera',
  'Shots you chose': 'Einstellungen, die Sie gewählt haben',
  'Between keyframes the pose comes from a spline through your own values, so it is smooth by construction rather than smoothed after the fact.': 'Zwischen den Keyframes stammt die Kameraposition aus einem Spline durch Ihre eigenen Werte — sie ist also von vornherein weich und wird nicht nachträglich geglättet.',
  'Steady through switchbacks': 'Ruhig durch Serpentinen',
  'The camera reads the direction the route takes over several seconds, so hairpins and GPS wander do not turn into camera shake.': 'Die Kamera liest die Richtung, die die Strecke über mehrere Sekunden nimmt, sodass Kehren und GPS-Schwankungen nicht zu Kamerawackeln werden.',
  'A subject-locked orbit': 'Ein auf das Motiv fixierter Orbit',
  'The ball only changes the angle, height and distance around your marker, so the subject cannot slide out of the shot while you frame it.': 'Der Ball ändert nur Winkel, Höhe und Abstand rund um Ihre Markierung, sodass das Motiv beim Einrichten nicht aus dem Bild rutschen kann.',
  'Keyboard-first': 'Tastatur zuerst',
  'Space, A/D, W/S, R/F and Enter cover the whole loop — pause, aim, save, move on.': 'Leertaste, A/D, W/S, R/F und Enter decken den ganzen Ablauf ab — pausieren, ausrichten, speichern, weiter.',
  'What a cinematic camera changes': 'Was eine filmische Kamera verändert',
  'A camera that follows a marker has to answer every move the marker makes. On a mountain route that means every switchback, and on a compressed replay a switchback lasts a fraction of a second — so the picture shakes even though the route is simply turning.': 'Eine Kamera, die einer Markierung folgt, muss auf jede ihrer Bewegungen reagieren. Auf einer Bergroute heißt das: auf jede Kehre — und in einer zeitlich gerafften Wiedergabe dauert eine Kehre den Bruchteil einer Sekunde. Das Bild wackelt also, obwohl die Strecke lediglich eine Kurve macht.',
  'Placing keyframes inverts that. You decide where the camera sits at a handful of moments, and the motion in between is interpolated rather than reacted. The result is a shot that holds still when you want it to and moves when you asked it to.': 'Keyframes drehen das um. Sie legen für eine Handvoll Momente fest, wo die Kamera steht, und die Bewegung dazwischen wird interpoliert statt erwidert. Das Ergebnis ist eine Einstellung, die stillsteht, wenn Sie das wollen, und sich bewegt, wenn Sie es verlangt haben.',
  'Keyframes are saved inside your .replay project file and are anchored to a point on the route rather than to a timestamp, so changing the clip length or reordering journey segments keeps every shot on the piece of route you framed it for.': 'Keyframes werden in Ihrer .replay-Projektdatei gespeichert und sind an einen Punkt auf der Strecke gebunden, nicht an einen Zeitstempel. Ändern Sie die Cliplänge oder die Reihenfolge der Tourabschnitte, bleibt jede Einstellung an dem Streckenstück, für das Sie sie eingerichtet haben.',
  'Do I need to place a keyframe for the whole route?': 'Muss ich für die ganze Route Keyframes setzen?',
  'No. With no keyframes the camera behaves like Follow Behind, and a single keyframe holds one locked-off shot for the entire replay. Add more only where you want the shot to change.': 'Nein. Ohne Keyframes verhält sich die Kamera wie „Folgen Sie hinterher“, und ein einzelner Keyframe hält eine feste Einstellung über die ganze Wiedergabe. Fügen Sie weitere nur dort hinzu, wo sich die Einstellung ändern soll.',
  'What happens between two keyframes?': 'Was passiert zwischen zwei Keyframes?',
  'The camera eases from one to the next. You can also set a keyframe to hold the previous shot until it is reached, or to move at a constant rate instead of easing.': 'Die Kamera gleitet sanft von einem zum nächsten. Ein Keyframe kann stattdessen auch die vorherige Einstellung halten, bis er erreicht ist, oder sich mit konstanter Geschwindigkeit bewegen.',
  'Can the camera keep pointing the same way as the route?': 'Kann die Kamera immer in Streckenrichtung zeigen?',
  'Yes. Each keyframe is either locked to the compass or held relative to the route, so a shot can stay over-the-shoulder as the trail turns.': 'Ja. Jeder Keyframe ist entweder auf den Kompass fixiert oder relativ zur Strecke gehalten, sodass eine Einstellung über die Schulter bleiben kann, während der Weg abbiegt.',
  'Does the exported video match the preview?': 'Entspricht das exportierte Video der Vorschau?',
  'Yes. The exported frames use the same camera evaluation as the live preview, so what you framed is what gets recorded.': 'Ja. Die exportierten Bilder verwenden dieselbe Kameraberechnung wie die Live-Vorschau — aufgezeichnet wird genau das, was Sie eingerichtet haben.',
  'My camera still moves more than I want. What should I change?': 'Meine Kamera bewegt sich immer noch mehr als gewünscht. Was soll ich ändern?',
  'Pull the Camera Stability slider toward Cinematic. It widens the window the camera smooths its path over. Pulling the camera further back also helps, because a wider shot can absorb more of the route wander.': 'Ziehen Sie den Regler „Kamerastabilität“ Richtung Filmisch. Das verbreitert das Fenster, über das die Kamera ihren Weg glättet. Auch ein größerer Abstand hilft, denn eine weitere Einstellung verkraftet mehr Streckenschwankung.',
};

function localize(value: unknown): unknown {
  if (typeof value === 'string') return germanCopy[value] ?? value;
  if (Array.isArray(value)) return value.map(localize);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, localize(item)]));
  }
  return value;
}

export const SEO_LANDING_PAGES_DE = localize(SEO_LANDING_PAGES) as Record<SeoLandingSlug, SeoLandingPageConfig>;
